### PR TITLE
[feat] Implement `sock_getaddrinfo` in `wasmedge_sys::async_wasi`

### PR DESCRIPTION
**Pull request by apepkuss**
In this PR, the following changes are introduced,

- Implements `sock_getaddrinfo` in `wasmedge_sys::async_wasi`.
- Refactors `ModuleDescriptor` and `PluginDescriptor` in `wasmedge-sys`.
- Improves `build_fedora` job in `bindings-rust` workflow.
- Renamed `sys_async_host_function_new` to `sys_async_host_function` in `wasmedge-macro`.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by apepkuss** [comment]
@L-jasmine Could you please help review this PR? Thanks a lot!

**Review by L-jasmine — APPROVED** [review]
LGTM

**Comment by apepkuss** [comment]
@L-jasmine Thanks for the review!

**Pull request merged**
