### PR TITLE
Migrate `async-wasi` into Rust SDK

### PR DESCRIPTION
**Pull request by apepkuss**
In this PR, the `async-wasi` project is merged into Rust SDK as a dependency.

### CODE REVIEW

**Comment by juntao** [comment]
flows summarize

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by apepkuss** [comment]
@L-jasmine Could you please help review this PR? Thanks a lot!

**Review by L-jasmine — APPROVED** [review]
LGTM

**Pull request merged**
