### PR TITLE
Update archives SHA and bump crates versions

### LINKED ISSUE #107: Difficulty pairing versions of the different SDK crates
There are several crates making up `wasmedge-sdk`, and their versions are not synchronized.
So far, the version table in the README has been helpful to workaround this, but recently it's become out of sync (e.g., v0.14.0 is not on the table).
Personally, I would prefer having all the crates using the same version, synchronized with WasmEdge's version.

### LINKED ISSUE #108: Artifacts for standalone are out of sync
The new 0.14.0 release does not update the SHA and version of the archives for the standalone feature, which are still pointing to the 0.13.5 archives.
https://github.com/WasmEdge/wasmedge-rust-sdk/blob/e9173cdd272b14a2540c15bdc67db5d71e82afb7/crates/wasmedge-sys/build.rs#L12-L29

### PR DESCRIPTION
**Pull request by jprendes**
Fix #108: Update the SHA values.
Fix #107: Update the readme and inline docs version table.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by jprendes** [comment]
@L-jasmine @hydai PTAL 🙏

**Review by hydai — APPROVED** [review]
LGTM. @L-jasmine PTAL

**Comment by L-jasmine** [comment]
LGTM
Thank you so much for your pr

**Review by L-jasmine — APPROVED** [review]

**Pull request merged**
