### PR TITLE
[refactor] Update the APIs related to sync host function creation

### PR DESCRIPTION
**Pull request by apepkuss**
In this PR, the following APIs are refactored:

- `wasmedge-sdk`
  - `Func::new`, `Func::wrap_func`
  - `ImportObjectBuilder::with_func`, `ImportObjectBuilder::with_func_by_type`
  - `PluginModuleBuilder::with_func`
- `wasmedge-sys`
  - `Function::create_sync_func`

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by L-jasmine — COMMENTED** [review]
Using `Option<&mut T>` to identify func's data as unsafe is because the lifetime of `T` is not bound to the lifetime of the `Function`, and `T` might be moved after creating the `Function`.

**Review by L-jasmine — APPROVED** [review]
Please fix it as soon as possible in the upcoming updates.

**Comment by apepkuss** [comment]
> Using `Option<&mut T>` to identify func's data as unsafe is because the lifetime of `T` is not bound to the lifetime of the `Function`, and `T` might be moved after creating the `Function`.

#27 tracks the issue. We'll fix it in another PR. Thanks a lot!

**Comment by apepkuss** [comment]
@L-jasmine Thanks for the review!

**Pull request merged**
